server:
  port: 9090

spring:
  application:
    name: liziyuan-shop-user
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace id
        namespace: liziyuan
        username: nacos # 访问账号
        password: nacos # 访问密码
